#!/bin/sh
# simple pre-commit hook: run quick tests
if [ -f "venv/Scripts/pytest" ]; then
    PYTEST="venv/Scripts/pytest"
elif [ -f "venv/bin/pytest" ]; then
    PYTEST="venv/bin/pytest"
else
    PYTEST="pytest"
fi
PYTHONPATH=src $PYTEST -q || exit 1
